name: Setup Nix
description: Setup Nix with caching
inputs:
  GITHUB_TOKEN:
    description: "The GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
      with:
        # Avoid rate limits
        github_access_token: "${{ inputs.GITHUB_TOKEN }}"

    - name: Source secrets
      shell: bash
      run: |
        nix develop "#cache" --accept-flake-config

    - name: Set up binary cache
      uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
      with:
        name: gekoke-dotfiles
        authToken: "${{ inputs.CACHIX_AUTH_TOKEN }}"
