name: Setup Nix
description: Setup Nix with caching
inputs:
  GITHUB_TOKEN:
    description: "The GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe # v31.10.3
      with:
        # Avoid rate limits
        github_access_token: "${{ inputs.GITHUB_TOKEN }}"

    - name: Source secrets
      shell: bash
      run: |
        nix develop "#cache" --accept-flake-config

    - name: Set up binary cache
      uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
      with:
        name: gekoke-dotfiles
        authToken: "${{ inputs.CACHIX_AUTH_TOKEN }}"
