name: update
on:
  workflow_dispatch:
  schedule:
    # At 00:00 on the 1st of every month
    - cron: '0 0 1 * *' 

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          commit-msg: "chore: update flake.lock"
          pr-title: "Update flake.lock"
          pr-labels: |
            bot
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.
            
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

